//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Models.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;Plant&gt;
        ///    &lt;Name&gt;Potato&lt;/Name&gt;
        ///          &lt;Phenology&gt;
        ///            &lt;Name&gt;Phenology&lt;/Name&gt;
        ///            &lt;StageBasedInterpolation&gt;
        ///              &lt;Name&gt;StageCode&lt;/Name&gt;
        ///              &lt;Stages&gt;
        ///                &lt;string&gt;Planting&lt;/string&gt;
        ///                &lt;string&gt;Peeping&lt;/string&gt;
        ///                &lt;string&gt;Emergence&lt;/string&gt;
        ///                &lt;string&gt;TuberInitiation&lt;/string&gt;
        ///                &lt;string&gt;FinalLeaf&lt;/string&gt;
        ///                &lt;string&gt;FullSenescence&lt;/string&gt;
        ///                &lt;string&gt;Maturity&lt;/string&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Potato {
            get {
                return ResourceManager.GetString("Potato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Plant15&gt;
        ///  &lt;Name&gt;Wheat&lt;/Name&gt;
        ///  &lt;AutoHarvest&gt;false&lt;/AutoHarvest&gt;
        ///  &lt;CropType&gt;Wheat&lt;/CropType&gt;
        ///  &lt;EOCropFactor&gt;1.5&lt;/EOCropFactor&gt;
        ///  &lt;NSupplyPreference&gt;active&lt;/NSupplyPreference&gt;
        ///  &lt;DoRetranslocationBeforeNDemand&gt;false&lt;/DoRetranslocationBeforeNDemand&gt;
        ///  &lt;RemovedByAnimal /&gt;
        ///  &lt;Population1&gt;
        ///    &lt;Name&gt;Population&lt;/Name&gt;
        ///    &lt;PhaseBasedSwitch&gt;
        ///      &lt;Name&gt;CropFailureStressPeriod&lt;/Name&gt;
        ///      &lt;Start&gt;Emergence&lt;/Start&gt;
        ///      &lt;End&gt;Flowering&lt;/End&gt;
        ///    &lt;/PhaseBasedSwitch&gt;
        ///    &lt;SoilTemperatureWeightedFunc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Wheat {
            get {
                return ResourceManager.GetString("Wheat", resourceCulture);
            }
        }
    }
}
