//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserInterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apsim_logo32 {
            get {
                object obj = ResourceManager.GetObject("apsim_logo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ApsimSummary {
            get {
                object obj = ResourceManager.GetObject("ApsimSummary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gfolder_32 {
            get {
                object obj = ResourceManager.GetObject("gfolder_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GraphToolbox {
            get {
                object obj = ResourceManager.GetObject("GraphToolbox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Graph&gt;
        ///  &lt;Name&gt;Graph&lt;/Name&gt;
        ///  &lt;LegendPosition&gt;BottomRight&lt;/LegendPosition&gt;
        ///  &lt;Axis&gt;
        ///    &lt;Type&gt;Left&lt;/Type&gt;
        ///    &lt;Title&gt;Depth (mm)&lt;/Title&gt;
        ///    &lt;Inverted&gt;true&lt;/Inverted&gt;
        ///  &lt;/Axis&gt;
        ///  &lt;Axis&gt;
        ///    &lt;Type&gt;Top&lt;/Type&gt;
        ///    &lt;Title&gt;Volumetric water (mm/mm)&lt;/Title&gt;
        ///    &lt;Inverted&gt;false&lt;/Inverted&gt;
        ///  &lt;/Axis&gt;
        ///  &lt;Series&gt;
        ///    &lt;Type&gt;Area&lt;/Type&gt;
        ///    &lt;Title&gt;Available water&lt;/Title&gt;
        ///    &lt;ShowInLegend&gt;true&lt;/ShowInLegend&gt;
        ///    &lt;XAxis&gt;Top&lt;/XAxis&gt;
        ///    &lt;YAxis&gt;Left&lt;/YAxis&gt;
        ///    &lt;ColourArgb&gt;-3479297&lt;/ColourArgb&gt;
        ///    &lt;Mark [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitialWaterGraph {
            get {
                return ResourceManager.GetString("InitialWaterGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ManagementToolbox {
            get {
                object obj = ResourceManager.GetObject("ManagementToolbox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream notes {
            get {
                return ResourceManager.GetStream("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #toc {
        ///  border-style: none;
        ///  font-family: Arial,Helvetica,sans-serif;
        ///  font-size: medium;
        ///}
        ///body {
        ///  background: white url(ApsruTile.jpg) repeat-y scroll left top;
        ///  font-family: Verdana,Arial,Helvetica,sans-serif;
        ///  font-size: 9pt;
        ///  color: black;
        ///  padding-left: 70px;
        ///  text-align: left;
        ///}
        ///p {
        ///  font-family: Verdana,Arial,Helvetica,sans-serif;
        ///  font-size: 9pt;
        ///  color: black;
        ///}
        ///table {
        ///  border: 0px solid #cccccc;
        ///  font-size: 9pt;
        ///  font-family: Arial,Helvetica,sans-serif;
        ///  bor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Plant2 {
            get {
                return ResourceManager.GetString("Plant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Report {
            get {
                object obj = ResourceManager.GetObject("Report", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StandardToolBox {
            get {
                object obj = ResourceManager.GetObject("StandardToolBox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StandardToolboxIcon {
            get {
                object obj = ResourceManager.GetObject("StandardToolboxIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream success {
            get {
                return ResourceManager.GetStream("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Test {
            get {
                object obj = ResourceManager.GetObject("Test", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;Graph&gt;
        ///        &lt;Name&gt;Graph&lt;/Name&gt;
        ///        &lt;LegendPosition&gt;BottomRight&lt;/LegendPosition&gt;
        ///        &lt;Axis&gt;
        ///          &lt;Type&gt;Left&lt;/Type&gt;
        ///          &lt;Title&gt;Depth (mm)&lt;/Title&gt;
        ///          &lt;Inverted&gt;true&lt;/Inverted&gt;
        ///        &lt;/Axis&gt;
        ///        &lt;Axis&gt;
        ///          &lt;Type&gt;Top&lt;/Type&gt;
        ///          &lt;Title&gt;Volumetric water (mm/mm)&lt;/Title&gt;
        ///          &lt;Inverted&gt;false&lt;/Inverted&gt;
        ///        &lt;/Axis&gt;
        ///        &lt;Series&gt;
        ///          &lt;Type&gt;Area&lt;/Type&gt;
        ///          &lt;Title&gt;LL15&lt;/Title&gt;
        ///          &lt;ShowInLegend&gt;false&lt;/ShowInLegend&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WaterGraph {
            get {
                return ResourceManager.GetString("WaterGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowDelete {
            get {
                object obj = ResourceManager.GetObject("WindowDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
