#' Convert Processed Soil Water Data to APSIM-X JSON Format
#'
#' @description
#' A universal serialization function that takes a processed soil moisture data frame 
#' (generated by \code{read_soil_water}) and formats it into a highly structured, 
#' clean JSON string. This output matches the exact array hierarchy expected by the 
#' APSIM Next Generation soil component text-injection engine.
#'
#' @param df_soil A data frame containing processed soil layers. Must include the columns:
#' \itemize{
#'   \item \code{Thickness}: Vector of layer depths in mm.
#'   \item \code{InitialWater_mean}: Vector of mean water fractions (0.0 - 1.0).
#' }
#'
#' @return A character string formatted as minified JSON containing parallel arrays 
#' for layer thicknesses and corresponding initial gravimetric water fractions.
#' @export
#'
#' @examples
#' \dontrun{
#' json_output <- soil_water_in_json(df_soil_water)
#' }
soil_water_into_json <- function(df_soil) {
  
  # ---- 1. SANITIZE INPUTS ----
  if (is.null(df_soil) || !is.data.frame(df_soil)) {
    stop("Error [soil_water_in_json]: Input 'df_soil' must be a valid, non-null data frame.")
  }
  
  required_cols <- c("Thickness", "InitialWater_mean")
  missing_cols <- setdiff(required_cols, names(df_soil))
  
  if (length(missing_cols) > 0) {
    stop(paste("Error [soil_water_in_json]: Input data frame is missing mandatory columns:", 
               paste(missing_cols, collapse = ", ")))
  }
  
  # ---- 2. BUILD STRUCTURED LIST FOR JSON SERIALIZATION ----
  # Isolating the parallel vector arrays explicitly maps them to clean JSON arrays
  soil_water_list <- list(
    InitialWater = list(
      Thickness    = as.numeric(df_soil$Thickness),
      InitialWater = as.numeric(df_soil$InitialWater_mean)
    )
  )
  
  # ---- 3. SERIALIZE TO MINIFIED JSON ----
  # auto_unbox = TRUE ensures single-element fields don't accidentally get wrapped in brackets []
  json_string <- jsonlite::toJSON(
    x = soil_water_list, 
    pretty = FALSE, 
    auto_unbox = TRUE
  )
  
  return(json_string)
}