pipeline {
	agent none
    stages {
		stage('CreateInstallers') {
			parallel {
				stage('Documentation') {
					agent {
						label "installation"
					}
					environment {
						APSIM_SITE_CREDS = credentials('apsim-site-creds')
						SOYBEAN_PASSWORD = credentials('soybean-validation-password')
					}
					steps {
						bat '''
							@echo off
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							cd ApsimX\\Jenkins
							call cleanup
							
							call build /r
							if errorlevel 1 exit /b 1
							
							call runTests Validation
							if errorlevel 1 exit /b 1
							
							call runTests Examples
							if errorlevel 1 exit /b 1
							
							..\\Bin\\CreateDocumentation.exe 
							if errorlevel 1 exit /b 1
						'''
					}
				}
				stage('Windows') {
					agent {
						label "installation"
					}
					environment {
						APSIM_SITE_CREDS = credentials('apsim-site-creds')
					}
					steps {
						bat '''
							@echo off
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							cd ApsimX\\Jenkins
							call cleanup
							call build /r
							if errorlevel 1 exit /b 1
							call createInstaller windows
						'''
					}
				}
				stage('MacOS') {
					agent {
						label "installation"
					}
					environment {
						APSIM_SITE_CREDS = credentials('apsim-site-creds')
					}
					steps {
						bat '''
							@echo off
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							cd ApsimX\\Jenkins
							call cleanup
							call build /r
							if errorlevel 1 exit /b 1
							call createInstaller macos
						'''
					}
				}
				stage('Debian') {
					agent {
						label "installation"
					}
					environment {
						APSIM_SITE_CREDS = credentials('apsim-site-creds')
					}
					steps {
						bat '''
							@echo off
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							cd ApsimX\\Jenkins
							call cleanup
							call build /r
							if errorlevel 1 exit /b 1
							call createInstaller debian
						'''
					}
				}
			}
		}
		stage('Deploy') {
			agent {
				label "installation"
			}
			environment {
				CHANGE_DB_CREDS = credentials('change-db-creds')
				NETLIFY_BUILD_HOOK = credentials('netlify-build-hook')
			}
			steps {
				bat '''
					@echo off
					if not exist ApsimX (
						git config --system core.longpaths true
						git clone https://github.com/APSIMInitiative/ApsimX ApsimX
					)
					cd ApsimX\\Jenkins
					call cleanup
					call deploy "%PULL_ID%" "%CHANGE_DB_CREDS_PSW%"
				'''
			}
		}
	}
}