pipeline {
	agent none
    stages {
		stage('CreateInstallers') {
			parallel {
				stage('Documentation') {
					agent {
						label "windows"
					}
					environment {
						APSIM_SITE_CREDS = credentials('apsim-site-creds')
					}
					steps {
						bat '''
							@echo off
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							cd ApsimX\\Jenkins
							cleanup
							build /r
							runTests Validation
							createDocumentation
							uploadDocumentation
						'''
					}
				}
				stage('Windows') {
					agent {
						label "windows"
					}
					environment {
						APSIM_SITE_CREDS = credentials('apsim-site-creds')
					}
					steps {
						bat '''
							@echo off
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							cd ApsimX\\Jenkins
							cleanup
							build /r
							createInstaller Windows
						'''
					}
				}
				stage('MacOS') {
					agent {
						label "windows"
					}
					environment {
						APSIM_SITE_CREDS = credentials('apsim-site-creds')
					}
					steps {
						bat '''
							@echo off
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							cd ApsimX\\Jenkins
							cleanup
							build /r
							createInstaller macos
						'''
					}
				}
				stage('Debian') {
					agent {
						label "windows"
					}
					environment {
						APSIM_SITE_CREDS = credentials('apsim-site-creds')
					}
					steps {
						bat '''
							@echo off
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							cd ApsimX\\Jenkins
							cleanup
							build /r
							createInstaller debian
						'''
					}
				}
			}
		}
		stage('Deploy') {
			agent {
				label "windows"
			}
			environment {
				CHANGE_DB_CREDS = credentials('change-db-creds')
			}
			steps {
				bat '''
					@echo off
					if not exist ApsimX (
						git config --system core.longpaths true
						git clone https://github.com/APSIMInitiative/ApsimX ApsimX
					)
					cd ApsimX\\Jenkins
					cleanup
					deploy "%PULL_ID%" "%CHANGE_DB_CREDS_PSW%"
				'''
			}
		}
	}
}