pipeline {
	agent none
    stages {
		stage('Deploy') {
			agent {
				label "installation"
			}
			environment {
				APSIM_SITE_CREDS = credentials('apsim-site-creds')
				CHANGE_DB_CREDS = credentials('change-db-creds')
				NETLIFY_BUILD_HOOK = credentials('netlify-build-hook')
			}
			steps {
				bat '''
					@echo off
					if not exist ApsimX (
						git config --system core.longpaths true
						git clone https://github.com/APSIMInitiative/ApsimX ApsimX
					)
					cd ApsimX\\Jenkins
					call cleanup
					call deploy
				'''
			}
		}
	}
}