blank_issues_enabled: false
contact_links:
  - name: "\U00002753 Ask a Question"
    url: https://github.com/APSIMInitiative/ApsimX/discussions
    about: "Please ask questions on our Discussions page"