name: "\U0001F454 Jenkins issue"
description: There is an issue with Jenkins
labels: ["jenkins"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Write Message and Upload Picture and/or Files Here
    validations:
      required: true


