name: "\U0001f195 New Feature"
description: Do you want to request a new feature
labels: ["newfeature"]
body:
  - type: textarea
    id: new-feature
    attributes:
      label: Describe the new feature
      placeholder: Write new feature details here
    validations:
      required: true
