name: "\U00002753 Question"
description: Do you have a question about this project
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: "Provide context about what your question applies to (Crop, Stock, Pasture, Swim3, CLEM etc) and any related files that can can inform us"
  - type: textarea
    id: question-area
    attributes:
      label: What is your question?
      placeholder: Write Message and Upload Files Here
    validations:
      required: true
