#################################################
# Docker image to generate ApsimX Documentation #
#################################################

FROM microsoft/dotnet-framework-build:4.7.1
SHELL ["powershell", "-Command"]

RUN Install-PackageProvider -Name Chocolatey            -Force -RequiredVersion 2.8.5.130;

RUN Set-ExecutionPolicy Bypass -Scope Process -Force; iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex; 	\
    choco feature disable –name showDownloadProgress;                                        							\
	choco feature enable -n allowGlobalConfirmation;                                         							\
    choco install 7zip;																									\
	choco install curl;

COPY doco.bat doco.bat

COPY ie.reg ie.reg

ENTRYPOINT ["doco.bat"]