pipeline {
    agent none 
    stages {
        stage('Build') {
			dockerfile {
				filename 'Dockerfile.build'
				dir 'Docker'
				label 'buildapsimx'
				additionalBuildArgs '-m 16g --cpu-count %NUMBER_OF_PROCESSORS%'
			}
            steps {
                bat '''
					call C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat
					set apsimx=C:\\ApsimX
					cd %apsimx%
					nuget restore
					copy /y %apsimx%\\DeploymentSupport\\Windows\\Bin64\\* %apsimx%\\Bin
					msbuild /m %apsimx%\\ApsimX.sln
				'''
            }
        }
    }
}