pipeline {
	agent none
    stages {
        stage('Build') {
			agent {
				label "windows && docker && build"
			}
			steps {
				bat '''
					@echo off
					echo.
					echo.
					echo	 ____        _ _     _ 
					echo	^|  _ \\      ^(_^) ^|   ^| ^|
					echo	^| ^|_^) ^|_   _ _^| ^| __^| ^|
					echo	^|  _ ^<^| ^| ^| ^| ^| ^|/ _^` ^|
					echo	^| ^|_^) ^| ^|_^| ^| ^| ^| ^(_^| ^|
					echo	^|____/ \\__,_^|_^|_^|\\__,_^|
					echo.
					echo.
					if not exist ApsimX (
						git config --system core.longpaths true
						git clone https://github.com/APSIMInitiative/ApsimX ApsimX
					)
					cd ApsimX
					git checkout -- .
					git clean -fxdq
					git pull origin master
					git fetch origin +refs/pull/*:refs/remotes/origin/pr/*
					git checkout %sha1%
					if %errorlevel% neq 0 (
						exit 1
					)
					cd ..
					if not exist APSIM.Shared (
						git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
					)
					git -C APSIM.Shared pull origin master
					
					docker build -m 16g -t buildapsimx ApsimX\\Docker\\build
					docker run -m 16g --cpu-count %NUMBER_OF_PROCESSORS% --cpu-percent 100 -e "PULL_ID=%ghprbPullId%" -v %cd%\\ApsimX:C:\\ApsimX -v %cd%\\APSIM.Shared:C:\\APSIM.Shared buildapsimx
				'''
				archiveArtifacts artifacts: 'ApsimX\\bin.zip', onlyIfSuccessful: true
				archiveArtifacts artifacts: 'ApsimX\\datetimestamp.txt', onlyIfSuccessful: true
			}
		}
		stage('RunTests') {
			parallel {
				stage('Prototypes') {
					agent {
						label "windows && docker"
					}
					steps {
						bat '''
							@echo off
							echo.
							echo.
							echo	  _____           _        _                         
							echo	 ^|  __ \\         ^| ^|      ^| ^|                        
							echo	 ^| ^|__) ^| __ ___ ^| ^|_ ___ ^| ^|_ _   _ _ __   ___  ___ 
							echo	 ^|  ___/ '__/ _ \\^| __/ _ \\^| __^| ^| ^| ^| '_ \\ / _ \\/ __^|
							echo	 ^| ^|   ^| ^| ^| (_) ^| ^|^| (_) ^| ^|_^| ^|_^| ^| ^|_) ^|  __/\\__ \\
							echo	 ^|_^|   ^|_^|  \\___/ \\__\\___/ \\__^|\\__, ^| .__/ \\___^|^|___/
							echo	                                __/ ^| ^|              
							echo	                               ^|___/^|_^|              
							echo.
							echo.
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							cd ApsimX
							git checkout -- .
							rem Don't cleanup nuget packages for now....this will be a problem in the long run!!
							git clean -fxdq -e packages
							git pull origin master
							git fetch origin +refs/pull/*:refs/remotes/origin/pr/*
							git checkout %sha1%
							if %errorlevel% neq 0 (
								exit 1
							)
							cd ..
						'''
						copyArtifacts filter: 'ApsimX\\bin.zip', fingerprintArtifacts: true, projectName: 'PullRequest', selector: specific('${BUILD_NUMBER}')
						bat '''
							@echo off
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							
							docker build -m 16g -t runtests ApsimX\\Docker\\runtests
							docker run -m 16g --cpu-count %NUMBER_OF_PROCESSORS% --cpu-percent 100 -v %cd%\\ApsimX:C:\\ApsimX -v %cd%\\APSIM.Shared:C:\\APSIM.Shared runtests Prototypes
						'''
					}
				}
				stage('UI') {
					agent {
						label "windows && docker"
					}
					steps {
						bat '''
							@echo off
							echo.
							echo.
							echo	  _    _ _____   _______        _       
							echo	 ^| ^|  ^| ^|_   _^| ^|__   __^|      ^| ^|      
							echo	 ^| ^|  ^| ^| ^| ^|      ^| ^| ___  ___^| ^|_ ___ 
							echo	 ^| ^|  ^| ^| ^| ^|      ^| ^|/ _ \\/ __^| __/ __^|
							echo	 ^| ^|__^| ^|_^| ^|_     ^| ^|  __/\\__ \\ ^|_\\__ \\
							echo	  \\____/^|_____^|    ^|_^|\\___^|^|___/\\__^|___/                                                
							echo.
							echo.
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							cd ApsimX
							git checkout -- .
							rem Don't cleanup nuget packages for now....this will be a problem in the long run!!
							git clean -fxdq -e packages
							git pull origin master
							git fetch origin +refs/pull/*:refs/remotes/origin/pr/*
							git checkout %sha1%
							if %errorlevel% neq 0 (
								exit 1
							)
							cd ..
						'''
						copyArtifacts filter: 'ApsimX\\bin.zip', fingerprintArtifacts: true, projectName: 'PullRequest', selector: specific('${BUILD_NUMBER}')
						bat '''
							@echo off
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							docker build -m 16g -t runtests ApsimX\\Docker\\runtests
							docker run -m 16g --cpu-count %NUMBER_OF_PROCESSORS% --cpu-percent 100 -v %cd%\\ApsimX:C:\\ApsimX -v %cd%\\APSIM.Shared:C:\\APSIM.Shared runtests UI
						'''
					}
				}
				stage('Validation') {
					agent {
						label "windows && docker"
					}
					steps {
						bat '''
							@echo off
							echo.
							echo.
							echo	 __      __   _ _     _       _   _             
							echo	 \\ \\    / /  ^| (_)   ^| ^|     ^| ^| (_)            
							echo	  \\ \\  / /_ _^| ^|_  __^| ^| __ _^| ^|_ _  ___  _ __  
							echo	   \\ \\/ / _` ^| ^| ^|/ _` ^|/ _` ^| __^| ^|/ _ \\^| '_ \\ 
							echo	    \\  / (_^| ^| ^| ^| (_^| ^| (_^| ^| ^|_^| ^| (_) ^| ^| ^| ^|
							echo	     \\/ \\__,_^|_^|_^|\\__,_^|\\__,_^|\\__^|_^|\\___/^|_^| ^|_^|                                                                                            
							echo.
							echo.
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							cd ApsimX
							git checkout -- .
							rem Don't cleanup nuget packages for now....this will be a problem in the long run!!
							git clean -fxdq -e packages
							git pull origin master
							git fetch origin +refs/pull/*:refs/remotes/origin/pr/*
							git checkout %sha1%
							if %errorlevel% neq 0 (
								exit 1
							)
							cd ..
						'''
						copyArtifacts filter: 'ApsimX\\bin.zip', fingerprintArtifacts: true, projectName: 'PullRequest', selector: specific('${BUILD_NUMBER}')
						copyArtifacts filter: 'ApsimX\\datetimestamp.txt', fingerprintArtifacts: true, projectName: 'PullRequest', selector: specific('${BUILD_NUMBER}')
						bat '''
							@echo off
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							set /P DATETIMESTAMP=<ApsimX\\datetimestamp.txt
							docker build -m 16g -t runtests ApsimX\\Docker\\runtests
							docker run -m 16g --cpu-count %NUMBER_OF_PROCESSORS% --cpu-percent 100 -e "DATETIMESTAMP=%DATETIMESTAMP%" -e "PULL_ID=%ghprbPullId%" -e "COMMIT_AUTHOR=%ghprbActualCommitAuthor%" -e "RUN_PERFORMANCE_TESTS=TRUE" -v %cd%\\ApsimX:C:\\ApsimX -v %cd%\\APSIM.Shared:C:\\APSIM.Shared runtests Validation
						'''
					}
				}
				stage('Unit Tests') {
					agent {
						label "windows && docker"
					}
					steps {
						bat '''
							@echo off
							echo.
							echo.
							echo	  _    _       _ _     _______        _       
							echo	 ^| ^|  ^| ^|     (_) ^|   ^|__   __^|      ^| ^|      
							echo	 ^| ^|  ^| ^|_ __  _^| ^|_     ^| ^| ___  ___^| ^|_ ___ 
							echo	 ^| ^|  ^| ^| '_ \\^| ^| __^|    ^| ^|/ _ \\/ __^| __/ __^|
							echo	 ^| ^|__^| ^| ^| ^| ^| ^| ^|_     ^| ^|  __/\\__ \\ ^|_\\__ \\
							echo	  \\____/^|_^| ^|_^|_^|\\__^|    ^|_^|\\___^|^|___/\\__^|___/                                                                                                                                     
							echo.
							echo.
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							cd ApsimX
							git checkout -- .
							rem Don't cleanup nuget packages for now....this will be a problem in the long run!!
							git clean -fxdq -e packages
							git pull origin master
							git fetch origin +refs/pull/*:refs/remotes/origin/pr/*
							git checkout %sha1%
							if %errorlevel% neq 0 (
								exit 1
							)
							cd ..
						'''
						copyArtifacts filter: 'ApsimX\\bin.zip', fingerprintArtifacts: true, projectName: 'PullRequest', selector: specific('${BUILD_NUMBER}')
						bat '''
							@echo off
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							docker build -m 16g -t runtests ApsimX\\Docker\\runtests
							docker run -m 16g --cpu-count %NUMBER_OF_PROCESSORS% --cpu-percent 100 -v %cd%\\ApsimX:C:\\ApsimX -v %cd%\\APSIM.Shared:C:\\APSIM.Shared runtests Unit
						'''
					}
				}
				stage('Run Examples') {
					agent {
						label "windows && docker"
					}
					steps {
						bat '''
							@echo off
							echo.
							echo.
							echo	  ______                           _           
							echo	 ^|  ____^|                         ^| ^|          
							echo	 ^| ^|__  __  ____ _ _ __ ___  _ __ ^| ^| ___  ___ 
							echo	 ^|  __^| \\ \\/ / _` ^| '_ ` _ \\^| '_ \\^| ^|/ _ \\/ __^|
							echo	 ^| ^|____ ^>  ^< (_^| ^| ^| ^| ^| ^| ^| ^|_) ^| ^|  __/\\__ \\
							echo	 ^|______/_/\\_\\__,_^|_^| ^|_^| ^|_^| .__/^|_^|\\___^|^|___/
							echo	                            ^| ^|                
							echo	                            ^|_^|                                                                                                                                                 
							echo.
							echo.
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							cd ApsimX
							git checkout -- .
							rem Don't cleanup nuget packages for now....this will be a problem in the long run!!
							git clean -fxdq -e packages
							git pull origin master
							git fetch origin +refs/pull/*:refs/remotes/origin/pr/*
							git checkout %sha1%
							if %errorlevel% neq 0 (
								exit 1
							)
							cd ..
						'''
						copyArtifacts filter: 'ApsimX\\bin.zip', fingerprintArtifacts: true, projectName: 'PullRequest', selector: specific('${BUILD_NUMBER}')
						bat '''
							@echo off
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							docker build -m 16g -t runtests ApsimX\\Docker\\runtests
							docker run -m 16g --cpu-count %NUMBER_OF_PROCESSORS% --cpu-percent 100 -v %cd%\\ApsimX:C:\\ApsimX -v %cd%\\APSIM.Shared:C:\\APSIM.Shared runtests Examples
						'''
					}
				}
			}
		}
    }
}