pipeline {
	agent none
    stages {
        stage('Build') {
			agent {
				label "windows && docker"
			}
			steps {
				bat '''
					if not exist ApsimX (
						git config --system core.longpaths true
						git clone https://github.com/APSIMInitiative/ApsimX ApsimX
					)
					
					cd ApsimX
					git checkout -- .
					git clean -xfd
					rem I assume the default repo name is origin.
					git pull origin master
					cd ..
					if not exist APSIM.Shared (
						git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
					)
					cd APSIM.Shared
					git pull origin master
					cd ..
					
					docker build -m 16g -t buildapsimx ApsimX\\Docker\\build
					docker run -m 16g --cpu-count %NUMBER_OF_PROCESSORS% --cpu-percent 100 -v %cd%\\ApsimX:C:\\ApsimX -v %cd%\\APSIM.Shared:C:\\APSIM.Shared buildapsimx
				'''
				archiveArtifacts artifacts: 'ApsimX\\bin.zip', onlyIfSuccessful: true
			}
		}
		stage('RunTests') {
			parallel {
				stage('Prototypes') {
					agent {
						label "windows && docker"
					}
					steps {
						bat '''
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							) else (
								cd ApsimX
								git reset --hard origin/master
								git clean -fxdq .\\Bin
								git pull origin master
								cd ..
							)
						'''
						copyArtifacts filter: 'ApsimX\\bin.zip', fingerprintArtifacts: true, projectName: 'master', selector: specific('${BUILD_NUMBER}')
						bat '''
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							
							docker build -m 16g -t runtests ApsimX\\Docker\\runtests
							docker run -m 16g --cpu-count %NUMBER_OF_PROCESSORS% --cpu-percent 100 -v %cd%\\ApsimX:C:\\ApsimX -v %cd%\\APSIM.Shared:C:\\APSIM.Shared runtests Prototypes
						'''
					}
				}
				stage('UI') {
					agent {
						label "windows && docker"
					}
					steps {
						bat '''
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							) else (
								cd ApsimX
								git reset --hard origin/master
								git clean -fxdq .\\Bin
								git pull origin master
								cd ..
							)
						'''
						copyArtifacts filter: 'ApsimX\\bin.zip', fingerprintArtifacts: true, projectName: 'master', selector: specific('${BUILD_NUMBER}')
						bat '''
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							docker build -m 16g -t runtests ApsimX\\Docker\\runtests
							docker run -m 16g --cpu-count %NUMBER_OF_PROCESSORS% --cpu-percent 100 -v %cd%\\ApsimX:C:\\ApsimX -v %cd%\\APSIM.Shared:C:\\APSIM.Shared runtests UI
						'''
					}
				}
				stage('Validation') {
					agent {
						label "windows && docker"
					}
					steps {
						bat '''
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							) else (
								cd ApsimX
								git reset --hard origin/master
								git clean -fxdq .\\Bin
								git pull origin master
								cd ..
							)
						'''
						copyArtifacts filter: 'ApsimX\\bin.zip', fingerprintArtifacts: true, projectName: 'master', selector: specific('${BUILD_NUMBER}')
						bat '''
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							docker build -m 16g -t runtests ApsimX\\Docker\\runtests
							docker run -m 16g --cpu-count %NUMBER_OF_PROCESSORS% --cpu-percent 100 -v %cd%\\ApsimX:C:\\ApsimX -v %cd%\\APSIM.Shared:C:\\APSIM.Shared runtests Validation
						'''
					}
				}
				stage('Unit Tests') {
					agent {
						label "windows && docker"
					}
					steps {
						bat '''
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							) else (
								cd ApsimX
								git reset --hard origin/master
								git clean -fxdq .\\Bin
								git pull origin master
								cd ..
							)
						'''
						copyArtifacts filter: 'ApsimX\\bin.zip', fingerprintArtifacts: true, projectName: 'master', selector: specific('${BUILD_NUMBER}')
						bat '''
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							docker build -m 16g -t runtests ApsimX\\Docker\\runtests
							docker run -m 16g --cpu-count %NUMBER_OF_PROCESSORS% --cpu-percent 100 -v %cd%\\ApsimX:C:\\ApsimX -v %cd%\\APSIM.Shared:C:\\APSIM.Shared runtests Unit
						'''
					}
				}
				stage('Run Examples') {
					agent {
						label "windows && docker"
					}
					steps {
						bat '''
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							) else (
								cd ApsimX
								git reset --hard origin/master
								git clean -fxdq .\\Bin
								git pull origin master
								cd ..
							)
						'''
						copyArtifacts filter: 'ApsimX\\bin.zip', fingerprintArtifacts: true, projectName: 'master', selector: specific('${BUILD_NUMBER}')
						bat '''
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							docker build -m 16g -t runtests ApsimX\\Docker\\runtests
							docker run -m 16g --cpu-count %NUMBER_OF_PROCESSORS% --cpu-percent 100 -v %cd%\\ApsimX:C:\\ApsimX -v %cd%\\APSIM.Shared:C:\\APSIM.Shared runtests Examples
						'''
					}
				}
				stage('Run Test Simulations') {
					agent {
						label "windows && docker"
					}
					steps {
						bat '''
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							) else (
								cd ApsimX
								git reset --hard origin/master
								git clean -fxdq .\\Bin
								git pull origin master
								cd ..
							)
						'''
						copyArtifacts filter: 'ApsimX\\bin.zip', fingerprintArtifacts: true, projectName: 'master', selector: specific('${BUILD_NUMBER}')
						bat '''
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							docker build -m 16g -t runtests ApsimX\\Docker\\runtests
							docker run -m 16g --cpu-count %NUMBER_OF_PROCESSORS% --cpu-percent 100 -v %cd%\\ApsimX:C:\\ApsimX -v %cd%\\APSIM.Shared:C:\\APSIM.Shared runtests Simulation
						'''
					}
				}
			}
		}
    }
}