using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using Models.Core;
using APSIM.Core;
using System.IO;
using Models.Storage;
using Models.Climate;
using APSIM.Shared.Utilities;
using Models.PostSimulationTools;
using Models.Utilities;

namespace Models.PreSimulationTools
{
    /// <summary>
    /// The Virtual model allows the loading of contents of one .apsimx file 
    /// into another.
    /// 
    /// ## DO NOT USE
    /// This model is still in testing and may change functionality in the near 
    /// future and break your files.
    /// </summary>
    [Serializable]
    [ViewName("UserInterface.Views.QuadView")]
    [PresenterName("UserInterface.Presenters.QuadPresenter")]
    [ValidParent(ParentType = typeof(Simulations))]
    public class Virtual : Model, IReferenceExternalFiles, ICodeEditor, IGenerateNodes
    {
        //Path to model to copy in
        private string _modelPath = "[Simulations]";

        /// <summary>The list of commands that are generated</summary>
        private string[] _commands = [];

        /// <summary>
        /// An internal flag that is set whenever a property is updated, so 
        /// that we can skip remaking nodes if nothing has changed on this 
        /// since it loaded.
        /// </summary>
        private bool _requiresUpdating = true;

        /// <summary>
        /// Filepath to apsimx file that we are loading from
        /// </summary>
        [JsonIgnore]
        public APSIMFilePath FilePath { get; set; } = new APSIMFilePath();

        /// <summary>
        /// Gets or sets the file to read from.
        /// </summary>
        [Description("File Path (*.apsimx)")]
        [Display(Type = DisplayType.FileName)]
        public string FileName
        {
            get { return FilePath.RelativeFilePath; }
            set 
            {
                FilePath.RelativeFilePath = value;
                _commands = [];
                _requiresUpdating = true;
            }
        }

        /// <summary>
        /// Model to find in the imported apsim to start the copy at.
        /// If [Simulations] is provided, all children will be copied over 
        /// instead as children of Import.
        /// Defaults to [Simulations]
        /// </summary>
        [Description("Model Path")]
        public string ModelPath { 
            get {return _modelPath; }
            set
            {
                _modelPath = value;
                _commands = [];
                _requiresUpdating = true;
            }
        }

        /// <summary>
        /// Getter for the list of commands generated by this model. 
        /// Cannot be changed with setter.
        /// </summary>
        [JsonIgnore]
        public IEnumerable<string> Code
        { 
            get { return _commands; } 
            set { return; }
        }

        /// <summary>
        /// Return our input filenames
        /// </summary>
        public IEnumerable<string> GetReferencedFileNames()
        {
            return [FileName];
        }

        /// <summary>
        /// Remove all paths from referenced filenames
        /// </summary>
        public void RemovePathsFromReferencedFileNames()
        {
            FilePath.RelativeFilePath = Path.GetFileName(FilePath.RelativeFilePath);
        }

        /// <summary>
        /// 
        /// </summary>
        public bool CreateNodes()
        {
            Virtual parentVirtual = Node.FindParent<Virtual>(recurse: true);
            if (parentVirtual != null)
                throw new Exception("Virtual cannot be placed under another Virtual node, potential cyclical loop.");

            _commands = GetCommands(this, FilePath.AbsoluteFilePath, ModelPath);

            string relativeDirectory = FilePath.StartDirectory;
            if (string.IsNullOrEmpty(relativeDirectory) || string.IsNullOrEmpty(FileName) || string.IsNullOrEmpty(ModelPath))
                return false;

            bool readOnly = ReadOnly;
            try
            {
                //Check if this model is read only, and disable temporarily while generating the children
                if (readOnly)
                    ReadOnly = false;
                
                //Lines will pull from _generatedCommads as a 1D array
                IEnumerable<IModelCommand> commands = CommandLanguage.StringToCommands(_commands, Parent.Node.Model, relativeDirectory);
                CommandProcessor.Run(commands, Parent.Node.Model, runner: null);
            }
            catch (Exception exception)
            {
                _commands = [];
                throw new Exception("Import failed to import from the input file.", exception);
            }
            finally //reset the read only status
            {
                ReadOnly = readOnly;
                _requiresUpdating = false;
            }
            return true;
        }

        /// <summary>
        /// 
        /// </summary>
        public bool DeleteNodes()
        {
            List<IModel> childrenToDelete = new List<IModel>();
            foreach(IModel child in Children)
                if (child.ReadOnly == true)
                    childrenToDelete.Add(child);
            foreach(IModel child in childrenToDelete)
                Node.RemoveChild(child.Node.Model);
            return true;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public bool RequiresUpdating()
        {
            return _requiresUpdating;
        }

        /// <summary>
        ///
        /// </summary>
        private static string[] GetCommands(Virtual import, string fileName, string path)
        {
            if (string.IsNullOrEmpty(fileName) || string.IsNullOrEmpty(path))
                return [];

            Simulations otherFile = FileFormat.ReadFromFile<Simulations>(fileName).Model as Simulations;
            List<IModel> childrenToImport = new List<IModel>();
            if (path.ToLower() == "simulations" || path.ToLower() == "[simulations]")
                childrenToImport.AddRange(otherFile.Children);
            else
            {
                VariableComposite model = otherFile.Node.GetObject(path, LocatorFlags.ModelsOnly);
                if (model != null)
                    childrenToImport.Add(model.Value as IModel);
            }

            List<string> commands = new List<string>();
            List<string> readOnlyCommands = new List<string>();
            foreach (IModel child in childrenToImport)
            {
                if (child != null)
                {
                    bool allowedToImport = true;
                    if (Folder.IsModelReplacementsFolder(child))
                        allowedToImport = false;
                    
                    if (allowedToImport)
                    {
                        commands.Add($"add [Simulations].{child.Name} from {fileName} to [{import.Name}]");
                        readOnlyCommands.Add($"[{import.Name}].{child.Name}.ReadOnly = True");
                        foreach(Node node in child.Node.Walk())
                            commands.AddRange(ModelSpecificCommands(import, node, fileName));
                    }
                }
            }
            commands.AddRange(readOnlyCommands);
            return commands.ToArray();
        }

        /// <summary>Called when the model is created.</summary>
        public override void OnCreated()
        {
            base.OnCreated();
            FilePath.SetStartDirectory(Path.GetDirectoryName(Node.FileName));
        }

        private static string[] ModelSpecificCommands(Virtual import, Node node, string fileName)
        {
            string localDirectory = Path.GetDirectoryName(import.Node.FileName);
            string referenceDirectory = Path.GetDirectoryName(fileName);

            List<string> commands = new List<string>();
            if (node.Model is DataStore dataStore)
            {
                commands.Add($"[{import.Name}].{dataStore.Name}.FileName = {Path.ChangeExtension(import.Node.FileName, ".db")}");
            }
            else if (node.Model is Weather weather)
            {
                string absolutePath = PathUtilities.GetAbsolutePath(weather.FileName, referenceDirectory);
                string relativePath = PathUtilities.GetRelativePath(absolutePath, localDirectory);
                string modelPath = weather.FullPath.Replace($".Simulations.", $"[{import.Name}].");
                commands.Add($"{modelPath}.FileName = {relativePath}");
            }
            else if (node.Model is ExcelInput excelInput)
            {
                List<string> newFileNames = new List<string>();
                foreach(string filename in excelInput.FileNames)
                {
                    string absolutePath = PathUtilities.GetAbsolutePath(filename, referenceDirectory);
                    string relativePath = PathUtilities.GetRelativePath(absolutePath, localDirectory);
                    newFileNames.Add(relativePath);
                }

                string modelPath = excelInput.FullPath.Replace($".Simulations.", $"[{import.Name}].");
                commands.Add($"{modelPath}.FileNames = {string.Join(',', newFileNames)}");
            }
            else if (node.Model is Observations observations)
            {
                List<string> newFileNames = new List<string>();
                foreach(string filename in observations.FileNames)
                {
                    string absolutePath = PathUtilities.GetAbsolutePath(filename, referenceDirectory);
                    string relativePath = PathUtilities.GetRelativePath(absolutePath, localDirectory);
                    newFileNames.Add(relativePath);
                }

                string modelPath = observations.FullPath.Replace($".Simulations.", $"[{import.Name}].");
                commands.Add($"{modelPath}.FileNames = {string.Join(',', newFileNames)}");
            }
            else if (node.Model is SetModelParamsBySimulation setModelParamsBySimulation)
            {
                string absolutePath = PathUtilities.GetAbsolutePath(setModelParamsBySimulation.ParameterFile, referenceDirectory);
                string relativePath = PathUtilities.GetRelativePath(absolutePath, localDirectory);
                string modelPath = setModelParamsBySimulation.FullPath.Replace($".Simulations.", $"[{import.Name}].");
                commands.Add($"{modelPath}.ParameterFile = {relativePath}");
            }
            return commands.ToArray();
        }
    }
}
