pipeline {
	agent none
    stages {
		stage('RunTests') {
			parallel {
				stage('Prototypes') {
					agent {
						label "windows"
					}
					steps {
						bat '''
							@echo off
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							cd ApsimX\Jenkins
							cleanup
							build
							runTests Prototypes
						'''
					}
				}
				stage('UI') {
					agent {
						label "windows"
					}
					steps {
						bat '''
							@echo off
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							cd ApsimX\Jenkins
							cleanup
							build
							runTests UI
						'''
					}
				}
				stage('Validation') {
					agent {
						label "windows"
					}
					steps {
						bat '''
							@echo off
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							cd ApsimX\Jenkins
							cleanup
							build
							runTests Validation
						'''
					}
				}
				stage('Unit Tests') {
					agent {
						label "windows"
					}
					steps {
						bat '''
							@echo off
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							cd ApsimX\Jenkins
							cleanup
							build
							runTests Unit
						'''
					}
				}
				stage('Run Examples') {
					agent {
						label "windows"
					}
					steps {
						bat '''
							@echo off
							rem We want to copy the build artifacts into ApsimX directory, however this directory may not exist yet.
							if not exist ApsimX (
								git config --system core.longpaths true
								git clone https://github.com/APSIMInitiative/ApsimX ApsimX
							)
							if not exist APSIM.Shared (
								git clone https://github.com/APSIMInitiative/APSIM.Shared APSIM.Shared
							)
							git -C APSIM.Shared pull origin master
							cd ApsimX\Jenkins
							cleanup
							build
							runTests Examples
						'''
					}
				}
			}
		}
    }
}