# NOTE: We should consider if these releases are add to the GitHub page under the 'Releases' section.

# NOTE: Andrew should have a container that builds these releases so individual steps should not be necessary.

# name: Build Releases
# permissions:
#   contents: read # access to check out code and install dependencies

# # Determines when this workflow is triggered. 
# on:
#   push:
#   pull_request:
#     branches: [ master ]

# jobs:
#   build-releases:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Build releases with release container
#         uses: apsiminitiative/release-container # TODO: needs real container put here.
      
    
