name: Build and test
permissions:
  contents: read # access to check out code and install dependencies

# Determines when this workflow is triggered. 
on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: build-and-test
    # Run all subsequent steps on the specified operating systems.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # 'macos-13' can be used but some tests involving doubles will require tolerance comparisons see: 
        # https://docs.nunit.org/articles/nunit/writing-tests/constraints/EqualConstraint.html#comparing-floating-point-values

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4

    - name: Build
      run: dotnet build --configuration Release
    
    - name: Test
      run: dotnet test