name: build and test
permissions:
  contents: read # access to check out code and install dependencies

on:
  push:
  pull_request:
    branches: [ master ]

# env:
#   DOTNET_VERSION: '8.0.x' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4

    - name: Build
      run: dotnet build --configuration Release
    
    - name: Test
      run: dotnet test