name: Test Digital Ag connection
on:
  workflow_dispatch:

jobs:
  test-digitalag-connection:
    runs-on: ubuntu-latest
    steps:
      - name: test connection with curl
        run: |
          result=$(curl -X GET "https://digitalag.csiro.au/workflo/antiforgery/token")
          echo "Result: $result"
          
